import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { RouterOutputs, TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "./_contexts/themeProvider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

type Theme = RouterOutputs["setting"]["retrieveSetting"][0];

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  let theme = { settingValue: "light" } as Theme;
  // const ret = (await api.setting.retrieveSetting({ settingName: "theme" }))[0];
  // if (ret !== undefined) theme = ret;
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${theme.settingValue}`}
      style={{ colorScheme: theme.settingValue }}
      suppressHydrationWarning
    >
      <body>
        <TRPCReactProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
