import "~/styles/globals.css";

import { Poppins } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { RouterOutputs, TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "./_contexts/themeProvider";
import { api } from "~/trpc/server";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

type Theme = RouterOutputs["setting"]["retrieveSetting"][0];

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  let theme = { settingValue: "light" } as Theme;
  // try {
  //   const ret = (
  //     await api.setting.retrieveSetting({ settingName: "theme" })
  //   )[0];
  //   if (ret !== undefined) theme = ret;
  // } catch (e) {
  //   console.log(e);
  // }
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${poppins.variable} ${theme.settingValue}`}
      style={{ colorScheme: theme.settingValue }}
      suppressHydrationWarning
    >
      <body>
        <TRPCReactProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
