/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMeasurementScanRouteImport } from './routes/api/measurement-scan'
import { Route as appLoginRouteImport } from './routes/(app)/login'
import { Route as appAuthedRouteRouteImport } from './routes/(app)/_authed/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as appAuthedDiaryRouteRouteImport } from './routes/(app)/_authed/diary/route'
import { Route as appAuthedDiaryIndexRouteImport } from './routes/(app)/_authed/diary/index'
import { Route as ApiCalendarGoogleCompleteRouteImport } from './routes/api/calendar/google/complete'
import { Route as appAuthedDiarySettingsRouteImport } from './routes/(app)/_authed/diary/settings'
import { Route as appAuthedDiaryRemindersRouteImport } from './routes/(app)/_authed/diary/reminders'
import { Route as appAuthedDiaryCalendarRouteImport } from './routes/(app)/_authed/diary/calendar'
import { Route as appAuthedDiarySettingsProfileRouteImport } from './routes/(app)/_authed/diary/settings.profile'
import { Route as appAuthedDiarySettingsNotificationsRouteImport } from './routes/(app)/_authed/diary/settings.notifications'
import { Route as appAuthedDiarySettingsAppearanceRouteImport } from './routes/(app)/_authed/diary/settings.appearance'
import { Route as appAuthedDiarySettingsAboutRouteImport } from './routes/(app)/_authed/diary/settings.about'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeasurementScanRoute = ApiMeasurementScanRouteImport.update({
  id: '/api/measurement-scan',
  path: '/api/measurement-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const appLoginRoute = appLoginRouteImport.update({
  id: '/(app)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appAuthedRouteRoute = appAuthedRouteRouteImport.update({
  id: '/(app)/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appAuthedDiaryRouteRoute = appAuthedDiaryRouteRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => appAuthedRouteRoute,
} as any)
const appAuthedDiaryIndexRoute = appAuthedDiaryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appAuthedDiaryRouteRoute,
} as any)
const ApiCalendarGoogleCompleteRoute =
  ApiCalendarGoogleCompleteRouteImport.update({
    id: '/api/calendar/google/complete',
    path: '/api/calendar/google/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const appAuthedDiarySettingsRoute = appAuthedDiarySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appAuthedDiaryRouteRoute,
} as any)
const appAuthedDiaryRemindersRoute = appAuthedDiaryRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => appAuthedDiaryRouteRoute,
} as any)
const appAuthedDiaryCalendarRoute = appAuthedDiaryCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => appAuthedDiaryRouteRoute,
} as any)
const appAuthedDiarySettingsProfileRoute =
  appAuthedDiarySettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => appAuthedDiarySettingsRoute,
  } as any)
const appAuthedDiarySettingsNotificationsRoute =
  appAuthedDiarySettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => appAuthedDiarySettingsRoute,
  } as any)
const appAuthedDiarySettingsAppearanceRoute =
  appAuthedDiarySettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => appAuthedDiarySettingsRoute,
  } as any)
const appAuthedDiarySettingsAboutRoute =
  appAuthedDiarySettingsAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => appAuthedDiarySettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof appLoginRoute
  '/api/measurement-scan': typeof ApiMeasurementScanRoute
  '/diary': typeof appAuthedDiaryRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/diary/calendar': typeof appAuthedDiaryCalendarRoute
  '/diary/reminders': typeof appAuthedDiaryRemindersRoute
  '/diary/settings': typeof appAuthedDiarySettingsRouteWithChildren
  '/api/calendar/google/complete': typeof ApiCalendarGoogleCompleteRoute
  '/diary/': typeof appAuthedDiaryIndexRoute
  '/diary/settings/about': typeof appAuthedDiarySettingsAboutRoute
  '/diary/settings/appearance': typeof appAuthedDiarySettingsAppearanceRoute
  '/diary/settings/notifications': typeof appAuthedDiarySettingsNotificationsRoute
  '/diary/settings/profile': typeof appAuthedDiarySettingsProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof appLoginRoute
  '/api/measurement-scan': typeof ApiMeasurementScanRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/diary/calendar': typeof appAuthedDiaryCalendarRoute
  '/diary/reminders': typeof appAuthedDiaryRemindersRoute
  '/diary/settings': typeof appAuthedDiarySettingsRouteWithChildren
  '/api/calendar/google/complete': typeof ApiCalendarGoogleCompleteRoute
  '/diary': typeof appAuthedDiaryIndexRoute
  '/diary/settings/about': typeof appAuthedDiarySettingsAboutRoute
  '/diary/settings/appearance': typeof appAuthedDiarySettingsAppearanceRoute
  '/diary/settings/notifications': typeof appAuthedDiarySettingsNotificationsRoute
  '/diary/settings/profile': typeof appAuthedDiarySettingsProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/_authed': typeof appAuthedRouteRouteWithChildren
  '/(app)/login': typeof appLoginRoute
  '/api/measurement-scan': typeof ApiMeasurementScanRoute
  '/(app)/_authed/diary': typeof appAuthedDiaryRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/_authed/diary/calendar': typeof appAuthedDiaryCalendarRoute
  '/(app)/_authed/diary/reminders': typeof appAuthedDiaryRemindersRoute
  '/(app)/_authed/diary/settings': typeof appAuthedDiarySettingsRouteWithChildren
  '/api/calendar/google/complete': typeof ApiCalendarGoogleCompleteRoute
  '/(app)/_authed/diary/': typeof appAuthedDiaryIndexRoute
  '/(app)/_authed/diary/settings/about': typeof appAuthedDiarySettingsAboutRoute
  '/(app)/_authed/diary/settings/appearance': typeof appAuthedDiarySettingsAppearanceRoute
  '/(app)/_authed/diary/settings/notifications': typeof appAuthedDiarySettingsNotificationsRoute
  '/(app)/_authed/diary/settings/profile': typeof appAuthedDiarySettingsProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/measurement-scan'
    | '/diary'
    | '/api/auth/$'
    | '/diary/calendar'
    | '/diary/reminders'
    | '/diary/settings'
    | '/api/calendar/google/complete'
    | '/diary/'
    | '/diary/settings/about'
    | '/diary/settings/appearance'
    | '/diary/settings/notifications'
    | '/diary/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/measurement-scan'
    | '/api/auth/$'
    | '/diary/calendar'
    | '/diary/reminders'
    | '/diary/settings'
    | '/api/calendar/google/complete'
    | '/diary'
    | '/diary/settings/about'
    | '/diary/settings/appearance'
    | '/diary/settings/notifications'
    | '/diary/settings/profile'
  id:
    | '__root__'
    | '/'
    | '/(app)/_authed'
    | '/(app)/login'
    | '/api/measurement-scan'
    | '/(app)/_authed/diary'
    | '/api/auth/$'
    | '/(app)/_authed/diary/calendar'
    | '/(app)/_authed/diary/reminders'
    | '/(app)/_authed/diary/settings'
    | '/api/calendar/google/complete'
    | '/(app)/_authed/diary/'
    | '/(app)/_authed/diary/settings/about'
    | '/(app)/_authed/diary/settings/appearance'
    | '/(app)/_authed/diary/settings/notifications'
    | '/(app)/_authed/diary/settings/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appAuthedRouteRoute: typeof appAuthedRouteRouteWithChildren
  appLoginRoute: typeof appLoginRoute
  ApiMeasurementScanRoute: typeof ApiMeasurementScanRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCalendarGoogleCompleteRoute: typeof ApiCalendarGoogleCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/measurement-scan': {
      id: '/api/measurement-scan'
      path: '/api/measurement-scan'
      fullPath: '/api/measurement-scan'
      preLoaderRoute: typeof ApiMeasurementScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/login': {
      id: '/(app)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof appLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_authed': {
      id: '/(app)/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_authed/diary': {
      id: '/(app)/_authed/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof appAuthedDiaryRouteRouteImport
      parentRoute: typeof appAuthedRouteRoute
    }
    '/(app)/_authed/diary/': {
      id: '/(app)/_authed/diary/'
      path: '/'
      fullPath: '/diary/'
      preLoaderRoute: typeof appAuthedDiaryIndexRouteImport
      parentRoute: typeof appAuthedDiaryRouteRoute
    }
    '/api/calendar/google/complete': {
      id: '/api/calendar/google/complete'
      path: '/api/calendar/google/complete'
      fullPath: '/api/calendar/google/complete'
      preLoaderRoute: typeof ApiCalendarGoogleCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_authed/diary/settings': {
      id: '/(app)/_authed/diary/settings'
      path: '/settings'
      fullPath: '/diary/settings'
      preLoaderRoute: typeof appAuthedDiarySettingsRouteImport
      parentRoute: typeof appAuthedDiaryRouteRoute
    }
    '/(app)/_authed/diary/reminders': {
      id: '/(app)/_authed/diary/reminders'
      path: '/reminders'
      fullPath: '/diary/reminders'
      preLoaderRoute: typeof appAuthedDiaryRemindersRouteImport
      parentRoute: typeof appAuthedDiaryRouteRoute
    }
    '/(app)/_authed/diary/calendar': {
      id: '/(app)/_authed/diary/calendar'
      path: '/calendar'
      fullPath: '/diary/calendar'
      preLoaderRoute: typeof appAuthedDiaryCalendarRouteImport
      parentRoute: typeof appAuthedDiaryRouteRoute
    }
    '/(app)/_authed/diary/settings/profile': {
      id: '/(app)/_authed/diary/settings/profile'
      path: '/profile'
      fullPath: '/diary/settings/profile'
      preLoaderRoute: typeof appAuthedDiarySettingsProfileRouteImport
      parentRoute: typeof appAuthedDiarySettingsRoute
    }
    '/(app)/_authed/diary/settings/notifications': {
      id: '/(app)/_authed/diary/settings/notifications'
      path: '/notifications'
      fullPath: '/diary/settings/notifications'
      preLoaderRoute: typeof appAuthedDiarySettingsNotificationsRouteImport
      parentRoute: typeof appAuthedDiarySettingsRoute
    }
    '/(app)/_authed/diary/settings/appearance': {
      id: '/(app)/_authed/diary/settings/appearance'
      path: '/appearance'
      fullPath: '/diary/settings/appearance'
      preLoaderRoute: typeof appAuthedDiarySettingsAppearanceRouteImport
      parentRoute: typeof appAuthedDiarySettingsRoute
    }
    '/(app)/_authed/diary/settings/about': {
      id: '/(app)/_authed/diary/settings/about'
      path: '/about'
      fullPath: '/diary/settings/about'
      preLoaderRoute: typeof appAuthedDiarySettingsAboutRouteImport
      parentRoute: typeof appAuthedDiarySettingsRoute
    }
  }
}

interface appAuthedDiarySettingsRouteChildren {
  appAuthedDiarySettingsAboutRoute: typeof appAuthedDiarySettingsAboutRoute
  appAuthedDiarySettingsAppearanceRoute: typeof appAuthedDiarySettingsAppearanceRoute
  appAuthedDiarySettingsNotificationsRoute: typeof appAuthedDiarySettingsNotificationsRoute
  appAuthedDiarySettingsProfileRoute: typeof appAuthedDiarySettingsProfileRoute
}

const appAuthedDiarySettingsRouteChildren: appAuthedDiarySettingsRouteChildren =
  {
    appAuthedDiarySettingsAboutRoute: appAuthedDiarySettingsAboutRoute,
    appAuthedDiarySettingsAppearanceRoute:
      appAuthedDiarySettingsAppearanceRoute,
    appAuthedDiarySettingsNotificationsRoute:
      appAuthedDiarySettingsNotificationsRoute,
    appAuthedDiarySettingsProfileRoute: appAuthedDiarySettingsProfileRoute,
  }

const appAuthedDiarySettingsRouteWithChildren =
  appAuthedDiarySettingsRoute._addFileChildren(
    appAuthedDiarySettingsRouteChildren,
  )

interface appAuthedDiaryRouteRouteChildren {
  appAuthedDiaryCalendarRoute: typeof appAuthedDiaryCalendarRoute
  appAuthedDiaryRemindersRoute: typeof appAuthedDiaryRemindersRoute
  appAuthedDiarySettingsRoute: typeof appAuthedDiarySettingsRouteWithChildren
  appAuthedDiaryIndexRoute: typeof appAuthedDiaryIndexRoute
}

const appAuthedDiaryRouteRouteChildren: appAuthedDiaryRouteRouteChildren = {
  appAuthedDiaryCalendarRoute: appAuthedDiaryCalendarRoute,
  appAuthedDiaryRemindersRoute: appAuthedDiaryRemindersRoute,
  appAuthedDiarySettingsRoute: appAuthedDiarySettingsRouteWithChildren,
  appAuthedDiaryIndexRoute: appAuthedDiaryIndexRoute,
}

const appAuthedDiaryRouteRouteWithChildren =
  appAuthedDiaryRouteRoute._addFileChildren(appAuthedDiaryRouteRouteChildren)

interface appAuthedRouteRouteChildren {
  appAuthedDiaryRouteRoute: typeof appAuthedDiaryRouteRouteWithChildren
}

const appAuthedRouteRouteChildren: appAuthedRouteRouteChildren = {
  appAuthedDiaryRouteRoute: appAuthedDiaryRouteRouteWithChildren,
}

const appAuthedRouteRouteWithChildren = appAuthedRouteRoute._addFileChildren(
  appAuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appAuthedRouteRoute: appAuthedRouteRouteWithChildren,
  appLoginRoute: appLoginRoute,
  ApiMeasurementScanRoute: ApiMeasurementScanRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCalendarGoogleCompleteRoute: ApiCalendarGoogleCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
