name: Supabase Ping

on:
  schedule:
    # Runs every 3 days at midnight UTC
    - cron: "0 0 */3 * *"
  workflow_dispatch: # allow manual triggering too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Ping Supabase with SQL
        run: |
          PGPASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }} \
          psql -h ${{ secrets.SUPABASE_DB_HOST }} \
               -U ${{ secrets.SUPABASE_DB_USER }} \
               -d ${{ secrets.SUPABASE_DB_NAME }} \
               -c "SELECT NOW();"
